declare var version: string;
declare var $: JQueryStatic;
declare var ls: Storage;
declare var realm: string | null;
declare var getUrls: never[];
declare var finUrls: never[];
declare var xcallback: never[];
declare var mapped: {};
declare var xcount: {};
declare var xmax: {};
declare var typedone: never[];
declare var xwait: never[];
declare var xequip: never[];
declare var fireequip: boolean;
declare var servergetcount: number;
declare var serverpostcount: number;
declare var suppliercount: number;
declare var processingtime: number;
declare var timeinterval: number;
declare var mousedown: boolean;
declare var $tron: HTMLElement;
declare var XMreload: boolean;
declare var xsup: never[];
declare var xsupcheck: {};
declare var urlUnitlist: string;
declare var blackmail: never[];
declare let _m: string[];
declare var companyid: number;
declare var equipfilter: never[];
interface IDictionary<T> {
    [index: string]: T;
}
interface IPolicy {
    func: () => void;
    save: string[][];
    order: string[][];
    name: string;
    group: string;
    wait: string[];
}
declare let policyJSON: IDictionary<IPolicy>;
declare function numberfy(variable: string): number;
declare function buildingShortener(): void;
declare function xpCookie(name: string): string | null;
declare function XioMaintenance(subidList: number[], policyNames: string[]): void;
declare function XioExport(): void;
declare function XioImport(): void;
declare function XioHoliday(): void;
declare function XioOverview(): void;
declare function topManagerStats(): void;
declare function preference(policies: string[]): boolean;
declare function preferencePages(html: JQuery, url: string): string[];
declare function salePrice(): void;
declare function salePolicy(): void;
declare function servicePrice(): void;
declare function serviceWithoutStockPrice(): void;
declare function incineratorPrice(): void;
declare function retailPrice(): void;
declare function prodSupply(): void;
declare function storeSupply(): void;
declare function wareSupply(): void;
declare function advertisement(): void;
declare function salary(): void;
declare function holiday(): void;
declare function training(): void;
declare function equipment(): void;
declare function technology(): void;
declare function research(): void;
declare function prodBooster(): void;
declare function politicAgitation(): void;
declare function wareSize(): void;
declare let xPrefPages: (jq: JQuery, url: string) => any[];
declare function XioScript(): boolean;
